/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Inquiry = {
  _id: string;
  _type: "inquiry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: string;
  name?: string;
  contact?: string;
  dates?: string;
  brief?: string;
  receivedAt?: string;
  read?: boolean;
};

export type Frame = {
  _id: string;
  _type: "frame";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  image: ImageWithAlt;
  ratio: "4/5" | "9/16" | "1/1" | "16/9";
  instagramUrl?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderRank?: string;
  title: string;
  slug: Slug;
  format: string;
  year: string;
  role: string;
  category: "dop" | "editor";
  cover: ImageWithAlt;
  frameGrabs?: Array<
    {
      _key: string;
    } & ImageWithAlt
  >;
  videoUrl?: string;
  showOnHome?: boolean;
  creditOnly?: boolean;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: ImageWithAlt;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  script: string;
  heading: string;
  intro: string;
  photo: ImageWithAlt;
  form?: {
    heading: string;
    typeQuestion: string;
    types?: Array<string>;
    nameLabel: string;
    contactLabel: string;
    datesLabel: string;
    briefLabel: string;
    submitLabel: string;
  };
  success?: {
    script: string;
    body: string;
    resetLabel: string;
  };
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    script: string;
    heading: string;
    body: string;
    ctaLabel: string;
    portrait: ImageWithAlt;
    polaroid: MediaSlot;
  };
  statement?: {
    headingPlain: string;
    headingAccent: string;
    paragraphs?: Array<string>;
    aside: string;
  };
  credits?: {
    headingBlock: HeadingBlock;
    imdbLabel: string;
    imdbUrl: string;
  };
  finale?: {
    script: string;
    sub: string;
    bgImage: ImageWithAlt;
  };
  seo?: Seo;
};

export type HeadingBlock = {
  _type: "headingBlock";
  script: string;
  heading: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type MediaSlot = {
  _type: "mediaSlot";
  kind: "image" | "video";
  image?: ImageWithAlt;
  video?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type FramesPage = {
  _id: string;
  _type: "framesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  script: string;
  heading: string;
  linkLabel: string;
  linkUrl: string;
  reelLabel: string;
  postLabel: string;
  seo?: Seo;
};

export type WorkPage = {
  _id: string;
  _type: "workPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  script: string;
  intro: string;
  filterAll: string;
  filterDop: string;
  filterEditor: string;
  showreel?: {
    poster: ImageWithAlt;
    videoUrl?: string;
    label: string;
    orderNotePrefix: string;
    orderNoteOverride?: string;
  };
  numberPrefix: string;
  projectCta: string;
  skills?: {
    headingBlock: HeadingBlock;
    items?: Array<
      {
        _key: string;
      } & Skill
    >;
  };
  projectPage?: {
    backLabel: string;
    reelPrefix: string;
    roleLabel: string;
    formatLabel: string;
    yearLabel: string;
    aspectLabel: string;
    grabsScript: string;
    grabsHeading: string;
    upNextScript: string;
  };
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    word: string;
    script: string;
    mainImage: ImageWithAlt;
    polaroidLeft: MediaSlot;
    polaroidRight: MediaSlot;
  };
  intro?: {
    script: string;
    heading: string;
    subline: string;
    body: string;
    ctaLabel: string;
    imageA: ImageWithAlt;
    imageB: ImageWithAlt;
  };
  reels?: {
    headingBlock: HeadingBlock;
    ctaLabel: string;
  };
  explore?: {
    headingBlock: HeadingBlock;
    cards?: Array<
      {
        _key: string;
      } & ExploreCard
    >;
  };
  currently?: {
    script: string;
    heading: string;
    body: string;
    ctaLabel: string;
    bgImage: ImageWithAlt;
  };
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandWord: string;
  brandScript: string;
  copyright: string;
  socials?: Array<
    {
      _key: string;
    } & Link
  >;
  management?: {
    label: string;
    handle: string;
    url: string;
  };
  dm?: {
    label: string;
    handle: string;
    url: string;
  };
  marqueeWords?: Array<string>;
  pages: Array<
    {
      _key: string;
    } & PageEntry
  >;
  menuScript: string;
  menuClose: string;
  menuSocialsLabel: string;
  menuPhoto: ImageWithAlt;
  leaderLeft: string;
  leaderRight: string;
  leaderSkip: string;
  showIntro?: boolean;
  showMarquee?: boolean;
  showGrain?: boolean;
  showRec?: boolean;
  seo?: Seo;
};

export type PageEntry = {
  _type: "pageEntry";
  key: "home" | "about" | "work" | "frames" | "contact";
  navLabel: string;
  menuLabel: string;
  preFooterScript?: string;
  preFooterLabel?: string;
};

export type Skill = {
  _type: "skill";
  label: string;
  media: MediaSlot;
  tilt: number;
};

export type ExploreCard = {
  _type: "exploreCard";
  label: string;
  sub: string;
  image: ImageWithAlt;
  target: "work" | "frames" | "contact" | "about";
};

export type Link = {
  _type: "link";
  label: string;
  url: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Inquiry
  | Frame
  | SanityImageAssetReference
  | ImageWithAlt
  | Project
  | Seo
  | Slug
  | ContactPage
  | AboutPage
  | HeadingBlock
  | SanityFileAssetReference
  | MediaSlot
  | FramesPage
  | WorkPage
  | HomePage
  | SiteSettings
  | PageEntry
  | Skill
  | ExploreCard
  | Link
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{  brandWord, brandScript, copyright,  socials[]{ label, url },  management{ label, handle, url }, dm{ label, handle, url },  marqueeWords,  pages[]{ key, navLabel, menuLabel, preFooterScript, preFooterLabel },  leaderLeft, leaderRight, leaderSkip, menuScript, menuClose, menuSocialsLabel,  menuPhoto {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }},  showIntro, showMarquee, showGrain, showRec,  seo { title, description, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} }}
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      brandWord: null;
      brandScript: null;
      copyright: null;
      socials: null;
      management: null;
      dm: null;
      marqueeWords: null;
      pages: null;
      leaderLeft: null;
      leaderRight: null;
      leaderSkip: null;
      menuScript: null;
      menuClose: null;
      menuSocialsLabel: null;
      menuPhoto: null;
      showIntro: null;
      showMarquee: null;
      showGrain: null;
      showRec: null;
      seo: null;
    }
  | {
      brandWord: null;
      brandScript: null;
      copyright: null;
      socials: null;
      management: null;
      dm: null;
      marqueeWords: null;
      pages: null;
      leaderLeft: null;
      leaderRight: null;
      leaderSkip: null;
      menuScript: null;
      menuClose: null;
      menuSocialsLabel: null;
      menuPhoto: null;
      showIntro: null;
      showMarquee: null;
      showGrain: null;
      showRec: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      brandWord: string;
      brandScript: string;
      copyright: string;
      socials: Array<{
        label: string;
        url: string;
      }> | null;
      management: {
        label: string;
        handle: string;
        url: string;
      } | null;
      dm: {
        label: string;
        handle: string;
        url: string;
      } | null;
      marqueeWords: Array<string> | null;
      pages: Array<{
        key: "about" | "contact" | "frames" | "home" | "work";
        navLabel: string;
        menuLabel: string;
        preFooterScript: string | null;
        preFooterLabel: string | null;
      }>;
      leaderLeft: string;
      leaderRight: string;
      leaderSkip: string;
      menuScript: string;
      menuClose: string;
      menuSocialsLabel: string;
      menuPhoto: {
        alt: string;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          url: string;
          extension: string;
          width: number | null;
          height: number | null;
          lqip: string | null;
        } | null;
      };
      showIntro: boolean | null;
      showMarquee: boolean | null;
      showGrain: boolean | null;
      showRec: boolean | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: HOME_QUERY
// Query: *[_id == "homePage"][0]{  hero{ word, script, mainImage {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, polaroidLeft { kind, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, "videoUrl": video.asset->url }, polaroidRight { kind, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, "videoUrl": video.asset->url } },  intro{ script, heading, subline, body, ctaLabel, imageA {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, imageB {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} },  reels{ headingBlock{ script, heading }, ctaLabel },  explore{ headingBlock{ script, heading }, cards[]{ label, sub, target, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} } },  currently{ script, heading, body, ctaLabel, bgImage {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} },  seo { title, description, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} }}
export type HOME_QUERY_RESULT =
  | {
      hero: null;
      intro: null;
      reels: null;
      explore: null;
      currently: null;
      seo: null;
    }
  | {
      hero: null;
      intro: null;
      reels: null;
      explore: null;
      currently: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      hero: {
        word: null;
        script: string;
        mainImage: null;
        polaroidLeft: null;
        polaroidRight: null;
      } | null;
      intro: null;
      reels: null;
      explore: null;
      currently: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      hero: {
        word: string;
        script: string;
        mainImage: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        };
        polaroidLeft: {
          kind: "image" | "video";
          image: {
            alt: string;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              url: string;
              extension: string;
              width: number | null;
              height: number | null;
              lqip: string | null;
            } | null;
          } | null;
          videoUrl: string | null;
        };
        polaroidRight: {
          kind: "image" | "video";
          image: {
            alt: string;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              url: string;
              extension: string;
              width: number | null;
              height: number | null;
              lqip: string | null;
            } | null;
          } | null;
          videoUrl: string | null;
        };
      } | null;
      intro: {
        script: string;
        heading: string;
        subline: string;
        body: string;
        ctaLabel: string;
        imageA: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        };
        imageB: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        };
      } | null;
      reels: {
        headingBlock: {
          script: string;
          heading: string;
        };
        ctaLabel: string;
      } | null;
      explore: {
        headingBlock: {
          script: string;
          heading: string;
        };
        cards: Array<{
          label: string;
          sub: string;
          target: "about" | "contact" | "frames" | "work";
          image: {
            alt: string;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              url: string;
              extension: string;
              width: number | null;
              height: number | null;
              lqip: string | null;
            } | null;
          };
        }> | null;
      } | null;
      currently: {
        script: string;
        heading: string;
        body: string;
        ctaLabel: string;
        bgImage: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        };
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: WORK_QUERY
// Query: *[_id == "workPage"][0]{  title, script, intro, filterAll, filterDop, filterEditor,  showreel{ poster {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, videoUrl, label, orderNotePrefix, orderNoteOverride },  numberPrefix, projectCta,  skills{ headingBlock{ script, heading }, items[]{ label, tilt, media { kind, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, "videoUrl": video.asset->url } } },  projectPage{ backLabel, reelPrefix, roleLabel, formatLabel, yearLabel, aspectLabel, grabsScript, grabsHeading, upNextScript },  seo { title, description, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} }}
export type WORK_QUERY_RESULT =
  | {
      title: null;
      script: null;
      intro: null;
      filterAll: null;
      filterDop: null;
      filterEditor: null;
      showreel: null;
      numberPrefix: null;
      projectCta: null;
      skills: null;
      projectPage: null;
      seo: null;
    }
  | {
      title: string | null;
      script: null;
      intro: null;
      filterAll: null;
      filterDop: null;
      filterEditor: null;
      showreel: null;
      numberPrefix: null;
      projectCta: null;
      skills: null;
      projectPage: null;
      seo: null;
    }
  | {
      title: null;
      script: null;
      intro: null;
      filterAll: null;
      filterDop: null;
      filterEditor: null;
      showreel: null;
      numberPrefix: null;
      projectCta: null;
      skills: null;
      projectPage: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      title: string;
      script: null;
      intro: null;
      filterAll: null;
      filterDop: null;
      filterEditor: null;
      showreel: null;
      numberPrefix: null;
      projectCta: null;
      skills: null;
      projectPage: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      title: null;
      script: string;
      intro: null;
      filterAll: null;
      filterDop: null;
      filterEditor: null;
      showreel: null;
      numberPrefix: null;
      projectCta: null;
      skills: null;
      projectPage: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      title: null;
      script: string;
      intro: string;
      filterAll: null;
      filterDop: null;
      filterEditor: null;
      showreel: null;
      numberPrefix: null;
      projectCta: null;
      skills: null;
      projectPage: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      title: null;
      script: null;
      intro: {
        script: string;
        heading: string;
        subline: string;
        body: string;
        ctaLabel: string;
        imageA: ImageWithAlt;
        imageB: ImageWithAlt;
      } | null;
      filterAll: null;
      filterDop: null;
      filterEditor: null;
      showreel: null;
      numberPrefix: null;
      projectCta: null;
      skills: null;
      projectPage: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      title: string;
      script: string;
      intro: string;
      filterAll: string;
      filterDop: string;
      filterEditor: string;
      showreel: {
        poster: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        };
        videoUrl: string | null;
        label: string;
        orderNotePrefix: string;
        orderNoteOverride: string | null;
      } | null;
      numberPrefix: string;
      projectCta: string;
      skills: {
        headingBlock: {
          script: string;
          heading: string;
        };
        items: Array<{
          label: string;
          tilt: number;
          media: {
            kind: "image" | "video";
            image: {
              alt: string;
              hotspot: SanityImageHotspot | null;
              crop: SanityImageCrop | null;
              asset: {
                _id: string;
                url: string;
                extension: string;
                width: number | null;
                height: number | null;
                lqip: string | null;
              } | null;
            } | null;
            videoUrl: string | null;
          };
        }> | null;
      } | null;
      projectPage: {
        backLabel: string;
        reelPrefix: string;
        roleLabel: string;
        formatLabel: string;
        yearLabel: string;
        aspectLabel: string;
        grabsScript: string;
        grabsHeading: string;
        upNextScript: string;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: FRAMES_PAGE_QUERY
// Query: *[_id == "framesPage"][0]{  script, heading, linkLabel, linkUrl, reelLabel, postLabel, seo { title, description, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} }}
export type FRAMES_PAGE_QUERY_RESULT =
  | {
      script: null;
      heading: null;
      linkLabel: null;
      linkUrl: null;
      reelLabel: null;
      postLabel: null;
      seo: null;
    }
  | {
      script: null;
      heading: null;
      linkLabel: null;
      linkUrl: null;
      reelLabel: null;
      postLabel: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      script: string;
      heading: null;
      linkLabel: null;
      linkUrl: null;
      reelLabel: null;
      postLabel: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      script: string;
      heading: string;
      linkLabel: null;
      linkUrl: null;
      reelLabel: null;
      postLabel: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      script: string;
      heading: string;
      linkLabel: string;
      linkUrl: string;
      reelLabel: string;
      postLabel: string;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: FRAMES_QUERY
// Query: *[_type == "frame"] | order(orderRank){  _id, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, ratio, instagramUrl}
export type FRAMES_QUERY_RESULT = Array<{
  _id: string;
  image: {
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      extension: string;
      width: number | null;
      height: number | null;
      lqip: string | null;
    } | null;
  };
  ratio: "1/1" | "16/9" | "4/5" | "9/16";
  instagramUrl: string | null;
}>;

// Source: ../web/lib/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_id == "aboutPage"][0]{  hero{ script, heading, body, ctaLabel, portrait {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, polaroid { kind, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, "videoUrl": video.asset->url } },  statement{ headingPlain, headingAccent, paragraphs, aside },  credits{ headingBlock{ script, heading }, imdbLabel, imdbUrl },  finale{ script, sub, bgImage {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} },  seo { title, description, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} }}
export type ABOUT_QUERY_RESULT =
  | {
      hero: null;
      statement: null;
      credits: null;
      finale: null;
      seo: null;
    }
  | {
      hero: null;
      statement: null;
      credits: null;
      finale: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      hero: {
        script: string;
        heading: null;
        body: null;
        ctaLabel: null;
        portrait: null;
        polaroid: null;
      } | null;
      statement: null;
      credits: null;
      finale: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      hero: {
        script: string;
        heading: string;
        body: string;
        ctaLabel: string;
        portrait: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        };
        polaroid: {
          kind: "image" | "video";
          image: {
            alt: string;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            asset: {
              _id: string;
              url: string;
              extension: string;
              width: number | null;
              height: number | null;
              lqip: string | null;
            } | null;
          } | null;
          videoUrl: string | null;
        };
      } | null;
      statement: {
        headingPlain: string;
        headingAccent: string;
        paragraphs: Array<string> | null;
        aside: string;
      } | null;
      credits: {
        headingBlock: {
          script: string;
          heading: string;
        };
        imdbLabel: string;
        imdbUrl: string;
      } | null;
      finale: {
        script: string;
        sub: string;
        bgImage: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        };
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: CONTACT_QUERY
// Query: *[_id == "contactPage"][0]{  script, heading, intro, photo {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }},  form{ heading, typeQuestion, types, nameLabel, contactLabel, datesLabel, briefLabel, submitLabel },  success{ script, body, resetLabel },  seo { title, description, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} }}
export type CONTACT_QUERY_RESULT =
  | {
      script: null;
      heading: null;
      intro: null;
      photo: null;
      form: null;
      success: null;
      seo: null;
    }
  | {
      script: null;
      heading: null;
      intro: null;
      photo: null;
      form: null;
      success: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      script: string;
      heading: null;
      intro: string;
      photo: null;
      form: null;
      success: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      script: null;
      heading: null;
      intro: {
        script: string;
        heading: string;
        subline: string;
        body: string;
        ctaLabel: string;
        imageA: ImageWithAlt;
        imageB: ImageWithAlt;
      } | null;
      photo: null;
      form: null;
      success: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      script: string;
      heading: string;
      intro: null;
      photo: null;
      form: null;
      success: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | {
      script: string;
      heading: string;
      intro: string;
      photo: {
        alt: string;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        asset: {
          _id: string;
          url: string;
          extension: string;
          width: number | null;
          height: number | null;
          lqip: string | null;
        } | null;
      };
      form: {
        heading: string;
        typeQuestion: string;
        types: Array<string> | null;
        nameLabel: string;
        contactLabel: string;
        datesLabel: string;
        briefLabel: string;
        submitLabel: string;
      } | null;
      success: {
        script: string;
        body: string;
        resetLabel: string;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          alt: string;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          asset: {
            _id: string;
            url: string;
            extension: string;
            width: number | null;
            height: number | null;
            lqip: string | null;
          } | null;
        } | null;
      } | null;
    }
  | null;

// Source: ../web/lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(orderRank) {  _id, title, "slug": slug.current, format, year, role, category,  cover {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, frameGrabs[] {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }}, videoUrl, showOnHome, creditOnly, seo { title, description, image {  alt, hotspot, crop,  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }} }}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  format: string;
  year: string;
  role: string;
  category: "dop" | "editor";
  cover: {
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      extension: string;
      width: number | null;
      height: number | null;
      lqip: string | null;
    } | null;
  };
  frameGrabs: Array<{
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    asset: {
      _id: string;
      url: string;
      extension: string;
      width: number | null;
      height: number | null;
      lqip: string | null;
    } | null;
  }> | null;
  videoUrl: string | null;
  showOnHome: boolean | null;
  creditOnly: boolean | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      asset: {
        _id: string;
        url: string;
        extension: string;
        width: number | null;
        height: number | null;
        lqip: string | null;
      } | null;
    } | null;
  } | null;
}>;

// Source: ../web/lib/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && creditOnly != true && defined(slug.current)]{ "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_id == "siteSettings"][0]{\n  brandWord, brandScript, copyright,\n  socials[]{ label, url },\n  management{ label, handle, url }, dm{ label, handle, url },\n  marqueeWords,\n  pages[]{ key, navLabel, menuLabel, preFooterScript, preFooterLabel },\n  leaderLeft, leaderRight, leaderSkip, menuScript, menuClose, menuSocialsLabel,\n  menuPhoto {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n},\n  showIntro, showMarquee, showGrain, showRec,\n  seo { title, description, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_id == "homePage"][0]{\n  hero{ word, script, mainImage {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, polaroidLeft { kind, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, "videoUrl": video.asset->url }, polaroidRight { kind, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, "videoUrl": video.asset->url } },\n  intro{ script, heading, subline, body, ctaLabel, imageA {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, imageB {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} },\n  reels{ headingBlock{ script, heading }, ctaLabel },\n  explore{ headingBlock{ script, heading }, cards[]{ label, sub, target, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} } },\n  currently{ script, heading, body, ctaLabel, bgImage {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} },\n  seo { title, description, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} }\n}': HOME_QUERY_RESULT;
    '*[_id == "workPage"][0]{\n  title, script, intro, filterAll, filterDop, filterEditor,\n  showreel{ poster {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, videoUrl, label, orderNotePrefix, orderNoteOverride },\n  numberPrefix, projectCta,\n  skills{ headingBlock{ script, heading }, items[]{ label, tilt, media { kind, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, "videoUrl": video.asset->url } } },\n  projectPage{ backLabel, reelPrefix, roleLabel, formatLabel, yearLabel, aspectLabel, grabsScript, grabsHeading, upNextScript },\n  seo { title, description, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} }\n}': WORK_QUERY_RESULT;
    '*[_id == "framesPage"][0]{\n  script, heading, linkLabel, linkUrl, reelLabel, postLabel, seo { title, description, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} }\n}': FRAMES_PAGE_QUERY_RESULT;
    '*[_type == "frame"] | order(orderRank){\n  _id, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, ratio, instagramUrl\n}': FRAMES_QUERY_RESULT;
    '*[_id == "aboutPage"][0]{\n  hero{ script, heading, body, ctaLabel, portrait {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, polaroid { kind, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, "videoUrl": video.asset->url } },\n  statement{ headingPlain, headingAccent, paragraphs, aside },\n  credits{ headingBlock{ script, heading }, imdbLabel, imdbUrl },\n  finale{ script, sub, bgImage {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} },\n  seo { title, description, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} }\n}': ABOUT_QUERY_RESULT;
    '*[_id == "contactPage"][0]{\n  script, heading, intro, photo {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n},\n  form{ heading, typeQuestion, types, nameLabel, contactLabel, datesLabel, briefLabel, submitLabel },\n  success{ script, body, resetLabel },\n  seo { title, description, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} }\n}': CONTACT_QUERY_RESULT;
    '*[_type == "project"] | order(orderRank) {\n  _id, title, "slug": slug.current, format, year, role, category,\n  cover {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, frameGrabs[] {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n}, videoUrl, showOnHome, creditOnly, seo { title, description, image {\n  alt, hotspot, crop,\n  asset->{ _id, url, extension, "width": metadata.dimensions.width, "height": metadata.dimensions.height, "lqip": metadata.lqip }\n} }\n}': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && creditOnly != true && defined(slug.current)]{ "slug": slug.current }': PROJECT_SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
